"""
Reproduce Figure 6 from "Towards Understanding Grokking" (Liu et al., 2022).

Figure 6 is a 2-D phase diagram over (weight_decay, learning_rate).
Each cell is classified into one of four phases:
    - Comprehension : both train & val accuracy are high, val generalizes early
    - Grokking      : both train & val accuracy are high, but val lags behind train
    - Memorization  : train accuracy is high, val accuracy stays low
    - Confusion     : both train & val accuracy are low

Usage example
-------------
# Run the full sweep with 2 cells in parallel:
python generate_grokking_phase_diagram.py \
    -dexp "x+y" --modulus 97 -tp 50 \
    -epoch 100000 \
    -w 2 \
    -o phase_diagram_output

# Plot results using the separate plotting script:
python plot_grokking_phase_diagram.py -o phase_diagram_output
"""

import os
import sys
import copy
import argparse
import logging
import json
import multiprocessing
from datetime import datetime
from itertools import product
from concurrent.futures import ProcessPoolExecutor, as_completed

import numpy as np
import torch

# ---------------------------------------------------------------------------
# Import project modules (same pattern as generate_grokking.py)
# ---------------------------------------------------------------------------
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from py_src import util, ml_setup
from py_src.ml_setup_base import transformer_for_grokking
from py_src.ml_setup_base.dataset_modular import ArithmeticDataset, ArithmeticIterator

# Re-use the helpers from the original script
from generate_grokking import (
    GrokkingParameters,
    train_grokking,
    generate_dataset,
    loading_dataset_from,
)

logger = logging.getLogger("generate_grokking_phase_diagram")

# ---------------------------------------------------------------------------
# Grid definition — 20 log-spaced values each
# ---------------------------------------------------------------------------
DEFAULT_LEARNING_RATES = list(np.logspace(-5, -2, 21))   # 1e-5 … 1e-2
DEFAULT_WEIGHT_DECAYS  = list(np.linspace(0, 20, 21))    # 0 … 20, linear


# ---------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------

def cell_output_dir(base: str, lr: float, wd: float) -> str:
    return os.path.join(base, f"lr{lr:.4e}_wd{wd:.4e}")


def cell_log_csv(base: str, lr: float, wd: float) -> str:
    return os.path.join(cell_output_dir(base, lr, wd), "00.log.csv")


def save_cell_metadata(cell_dir: str, lr: float, wd: float, extra: dict = None):
    """Persist (lr, wd) and any extra info so the plotting script needs no CLI args."""
    meta = {"learning_rate": lr, "weight_decay": wd}
    if extra:
        meta.update(extra)
    with open(os.path.join(cell_dir, "meta.json"), "w") as f:
        json.dump(meta, f, indent=2)


# ---------------------------------------------------------------------------
# Worker function — must be a top-level function for pickle (spawn)
# ---------------------------------------------------------------------------

def _worker(
    lr: float,
    wd: float,
    output_folder_path: str,
    # dataset args (re-generate inside worker to avoid cross-process sharing)
    dataset_path: str,
    train_pct: float,
    dataset_exp: str,
    modulus: int,
    split_type: str,
    operand_length,
    # training args
    epoch: int,
    batchsize,
    model_type: str,
    # model override args
    m_nlayer, m_n_heads, m_d_model, m_context_len,
    # misc
    random_seed,
):
    """
    Train a single (lr, wd) cell.  Runs in its own spawned process so that
    CUDA contexts are fully isolated between parallel jobs.
    """
    # Per-worker logging (each worker writes to its own cell log file too)
    worker_logger = logging.getLogger(f"worker_lr{lr:.2e}_wd{wd:.2e}")
    util.set_logging(worker_logger, f"lr{lr:.2e}_wd{wd:.2e}")

    if random_seed is not None:
        util.set_seed(random_seed, worker_logger)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # Each worker builds its own ml_setup (model weights are re-initialised
    # anyway, but we need the setup object for model_name / dataset_name /
    # training_batch_size).
    current_ml_setup = ml_setup.get_ml_setup_from_config(
        model_type, dataset_type="arithmetic_exp_unknown", device=device)

    # Dataset — either load from path or regenerate.
    # Workers that share a dataset_path can safely load the same files
    # concurrently (read-only).  If generating, each worker writes into its
    # own cell_dir so there is no collision.
    cell_dir = cell_output_dir(output_folder_path, lr, wd)
    os.makedirs(cell_dir, exist_ok=True)

    if dataset_path is not None:
        train_ds, val_ds = loading_dataset_from(dataset_path)
    else:
        # Re-use the dataset that was already generated by the main process
        # (saved next to grid_spec.json).  We detect it by the name the
        # ArithmeticDataset would have used.
        #
        # Fallback: generate fresh inside cell_dir (slower but always correct).
        train_ds, val_ds = generate_dataset(
            cell_dir, train_pct, dataset_exp, modulus, split_type, operand_length)

    save_cell_metadata(cell_dir, lr, wd, extra={
        "modulus":    modulus,
        "train_pct":  train_pct,
        "epoch":      epoch,
        "model_type": model_type,
    })

    # Build model
    model = copy.deepcopy(current_ml_setup.model)
    if any(x is not None for x in [m_nlayer, m_n_heads, m_d_model, m_context_len]):
        m_nlayer      = m_nlayer      or 2
        m_n_heads     = m_n_heads     or 4
        m_d_model     = m_d_model     or 128
        m_context_len = m_context_len or 50
        model = transformer_for_grokking.Transformer(
            n_layers=m_nlayer, n_heads=m_n_heads,
            d_model=m_d_model, max_context_len=m_context_len)
    current_ml_setup.re_initialize_model(model)
    model.to(device)

    batch_size = current_ml_setup.training_batch_size if batchsize is None else batchsize
    train_dl = ArithmeticIterator(train_ds, device, batchsize_hint=batch_size)
    val_dl   = ArithmeticIterator(val_ds,   device, batchsize_hint=batch_size)

    params = GrokkingParameters()
    params.set_env(cell_dir, True, logger=worker_logger)
    params.set_ml_env(model, current_ml_setup.model_name,
                      current_ml_setup.dataset_name, train_ds.tokenizer)
    params.set_ml_hyperparameter(
        learning_rate=lr,
        weight_decay=wd,
        min_lr=lr,          # constant LR (cosine bottoms out at lr itself)
        warmup_epoch=10,
        total_epoch=epoch,
    )
    params.set_dataloader(train_dl, val_dl)
    params.set_model_save("00", save_format="none")

    worker_logger.info(f"training cell lr={lr:.4e}  wd={wd:.4e}")
    train_grokking(params)
    return lr, wd   # returned to the main process for progress logging


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    # 'spawn' is required for CUDA safety; also works correctly on CPU-only.
    multiprocessing.set_start_method("spawn", force=True)

    parser = argparse.ArgumentParser(
        description="Sweep LR × WD to reproduce the grokking phase diagram (Figure 6)")

    # ---- output ----
    parser.add_argument("-o", "--output_folder_name", default=None)

    # ---- parallelism ----
    parser.add_argument("-w", "--workers", type=int, default=2,
                        help="Number of cells to train in parallel (default: 2). "
                             "Set to 1 for fully sequential execution. "
                             "With CUDA, keep this ≤ number of available GPUs "
                             "unless you intend multiple jobs per GPU.")

    # ---- grid ----
    parser.add_argument("-lrs", "--learning_rates", nargs="+", type=float,
                        default=DEFAULT_LEARNING_RATES,
                        help="Learning rates to sweep "
                             "(default: 20 log-spaced from 1e-5 to 1e-2)")
    parser.add_argument("-wds", "--weight_decays", nargs="+", type=float,
                        default=DEFAULT_WEIGHT_DECAYS,
                        help="Weight decay values to sweep "
                             "(default: 20 linear-spaced from 0 to 20)")

    # ---- dataset ----
    parser.add_argument("-dpath", "--dataset_path", type=str, default=None)
    parser.add_argument("-dexp",  "--dataset_exp",  type=str, default=None)
    parser.add_argument("--modulus",   type=int,   default=97)
    parser.add_argument("-tp", "--train_pct", type=float, default=50)
    parser.add_argument("-st", "--split_type", type=str, default="random",
                        choices=["random", "chessboard", "updown", "leftright",
                                 "tl_to_br", "tr_to_bl", "interlace_row",
                                 "interlace_col", "chessboard_random"])
    parser.add_argument("-ol", "--operand_length", type=int, default=None)

    # ---- training ----
    parser.add_argument("-epoch", "--epoch",   type=int, default=100000)
    parser.add_argument("-bs",    "--batchsize", type=int, default=None)
    parser.add_argument("-m", "--model_type",  type=str,
                        default="transformer_for_grokking")

    # ---- optional model overrides ----
    parser.add_argument("--m_nlayer",      default=None, type=int)
    parser.add_argument("--m_n_heads",     default=None, type=int)
    parser.add_argument("--m_d_model",     default=None, type=int)
    parser.add_argument("--m_context_len", default=None, type=int)

    # ---- misc ----
    parser.add_argument("-s", "--random_seed", type=int, default=None)

    args = parser.parse_args()

    # ---- logging ----
    util.set_logging(logger, "main")
    logger.info("phase diagram sweep starting")

    if args.random_seed is not None:
        util.set_seed(args.random_seed, logger)

    # ---- output folder ----
    if args.output_folder_name is None:
        ts = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        args.output_folder_path = os.path.join(
            os.curdir, f"generate_grokking_phase_diagram_{ts}")
    else:
        args.output_folder_path = os.path.join(os.curdir, args.output_folder_name)
    os.makedirs(args.output_folder_path, exist_ok=True)

    with open(os.path.join(args.output_folder_path, "command.txt"), "w") as f:
        f.write(" ".join(sys.argv))

    grid_spec = {
        "learning_rates": args.learning_rates,
        "weight_decays":  args.weight_decays,
    }
    with open(os.path.join(args.output_folder_path, "grid_spec.json"), "w") as f:
        json.dump(grid_spec, f, indent=2)

    learning_rates = args.learning_rates
    weight_decays  = args.weight_decays
    total_cells    = len(learning_rates) * len(weight_decays)
    logger.info(f"Grid: {len(learning_rates)} LRs × {len(weight_decays)} WDs "
                f"= {total_cells} cells,  workers={args.workers}")

    # ---- pre-generate the shared dataset in the main process ----
    # Workers that don't receive a dataset_path will each call generate_dataset
    # inside their own cell_dir (perfectly safe, just generates N copies of the
    # same split).  If you prefer a single shared copy, generate it here and
    # pass its path via dataset_path.
    dataset_path = args.dataset_path
    if dataset_path is None and args.dataset_exp is not None:
        # Generate once here; pass the path to workers so they all share it.
        device_main = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        train_ds, _ = generate_dataset(
            args.output_folder_path,
            args.train_pct,
            args.dataset_exp,
            args.modulus,
            args.split_type,
            args.operand_length,
        )
        dataset_path = os.path.join(args.output_folder_path, train_ds.name)
        logger.info(f"Dataset pre-generated at {dataset_path}")

    # ---- build pending cell list (skip already-done cells) ----
    pending = [
        (lr, wd)
        for lr, wd in product(learning_rates, weight_decays)
        if not os.path.exists(cell_log_csv(args.output_folder_path, lr, wd))
    ]
    skipped = total_cells - len(pending)
    if skipped:
        logger.info(f"Skipping {skipped} already-completed cells")
    logger.info(f"Submitting {len(pending)} cells to pool (workers={args.workers})")

    # ---- shared kwargs for every worker ----
    worker_kwargs = dict(
        output_folder_path=args.output_folder_path,
        dataset_path=dataset_path,
        train_pct=args.train_pct,
        dataset_exp=args.dataset_exp,
        modulus=args.modulus,
        split_type=args.split_type,
        operand_length=args.operand_length,
        epoch=args.epoch,
        min_lr=None,        # worker uses lr as min_lr (constant schedule)
        batchsize=args.batchsize,
        model_type=args.model_type,
        m_nlayer=args.m_nlayer,
        m_n_heads=args.m_n_heads,
        m_d_model=args.m_d_model,
        m_context_len=args.m_context_len,
        random_seed=args.random_seed,
    )

    # ---- dispatch ----
    completed = 0
    failed    = 0
    with ProcessPoolExecutor(max_workers=args.workers) as pool:
        futures = {
            pool.submit(_worker, lr, wd, **worker_kwargs): (lr, wd)
            for lr, wd in pending
        }
        for future in as_completed(futures):
            lr, wd = futures[future]
            try:
                future.result()
                completed += 1
                logger.info(
                    f"[{completed + skipped}/{total_cells}] done "
                    f"lr={lr:.4e} wd={wd:.4e}")
            except Exception as exc:
                failed += 1
                logger.error(
                    f"Cell lr={lr:.4e} wd={wd:.4e} raised an exception: {exc}",
                    exc_info=True)

    logger.info(
        f"Sweep complete. "
        f"Completed={completed}  Skipped={skipped}  Failed={failed}  "
        f"Total={total_cells}")
    if failed:
        logger.warning(
            f"{failed} cells failed. Re-run the script to retry them "
            f"(completed cells are skipped automatically).")
    logger.info("Run plot_grokking_phase_diagram.py to visualise.")
